AWSTemplateFormatVersion: '2010-09-09'
Resources:
  HelloWorldLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          exports.handler = async (event) => {
              return 'Hello, World!';
          };
      Handler: index.handler
      Runtime: nodejs14.x
      Role: !GetAtt HelloWorldLambdaExecutionRole.Arn

  HelloWorldLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      Policies:
      - PolicyName: HelloWorldLambdaExecutionPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            Resource: '*'

  NotificationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: HelloWorldAlarmTopic

  Alarm231min:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'First triggered at 12:00, will alarm at 12:02'
      Namespace: 'AWS/Lambda'
      MetricName: 'Invocations'
      Statistic: 'SampleCount'
      Period: '60'
      EvaluationPeriods: '3'
      DatapointsToAlarm: '2'
      Threshold: '1'
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - Ref: NotificationTopic
      Dimensions:
        - Name: 'FunctionName'
          Value: !Ref HelloWorldLambdaFunction

  Alarm235min:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'First triggered at 12:00, will alarm at 12:10'
      Namespace: 'AWS/Lambda'
      MetricName: 'Invocations'
      Statistic: 'SampleCount'
      Period: '300'
      EvaluationPeriods: '3'
      DatapointsToAlarm: '2'
      Threshold: '1'
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - Ref: NotificationTopic
      Dimensions:
        - Name: 'FunctionName'
          Value: !Ref HelloWorldLambdaFunction

  Alarm2310min:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'First triggered at 12:00, will alarm at 12:20'
      Namespace: 'AWS/Lambda'
      MetricName: 'Invocations'
      Statistic: 'SampleCount'
      Period: '600'
      EvaluationPeriods: '3'
      DatapointsToAlarm: '2'
      Threshold: '1'
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - Ref: NotificationTopic
      Dimensions:
        - Name: 'FunctionName'
          Value: !Ref HelloWorldLambdaFunction

  Alarm2315min:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'First triggered at 12:00, will alarm at 12:30'
      Namespace: 'AWS/Lambda'
      MetricName: 'Invocations'
      Statistic: 'SampleCount'
      Period: '900'
      EvaluationPeriods: '3'
      DatapointsToAlarm: '2'
      Threshold: '1'
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - Ref: NotificationTopic
      Dimensions:
        - Name: 'FunctionName'
          Value: !Ref HelloWorldLambdaFunction

  Alarm331min:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'First triggered at 12:00, will alarm at 12:02'
      Namespace: 'AWS/Lambda'
      MetricName: 'Invocations'
      Statistic: 'SampleCount'
      Period: '60'
      EvaluationPeriods: '3'
      DatapointsToAlarm: '3'
      Threshold: '1'
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - Ref: NotificationTopic
      Dimensions:
        - Name: 'FunctionName'
          Value: !Ref HelloWorldLambdaFunction

  Alarm335min:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'First triggered at 12:00, will alarm at 12:15'
      Namespace: 'AWS/Lambda'
      MetricName: 'Invocations'
      Statistic: 'SampleCount'
      Period: '300'
      EvaluationPeriods: '3'
      DatapointsToAlarm: '3'
      Threshold: '1'
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - Ref: NotificationTopic
      Dimensions:
        - Name: 'FunctionName'
          Value: !Ref HelloWorldLambdaFunction

  Alarm3310min:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'First triggered at 12:00, will alarm at 12:30'
      Namespace: 'AWS/Lambda'
      MetricName: 'Invocations'
      Statistic: 'SampleCount'
      Period: '600'
      EvaluationPeriods: '3'
      DatapointsToAlarm: '3'
      Threshold: '1'
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - Ref: NotificationTopic
      Dimensions:
        - Name: 'FunctionName'
          Value: !Ref HelloWorldLambdaFunction

  Alarm3315min:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'First triggered at 12:00, will alarm at 12:45'
      Namespace: 'AWS/Lambda'
      MetricName: 'Invocations'
      Statistic: 'SampleCount'
      Period: '900'
      EvaluationPeriods: '3'
      DatapointsToAlarm: '3'
      Threshold: '1'
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - Ref: NotificationTopic
      Dimensions:
        - Name: 'FunctionName'
          Value: !Ref HelloWorldLambdaFunction
